Repository hawks-atlanta/metadata-scala, pull requests merged in 2023-08, with the labels that each got.

#4 chore: Initial project
  .dockerignore
  .gitignore
  Dockerfile
  Makefile
  README.md
  build.sbt
  project/assembly.sbt
  project/build.properties
  project/plugins.sbt
  src/main/scala/Main.scala
  src/main/scala/fruit/application/UseCases.scala
  src/main/scala/fruit/domain/Fruit.scala
  src/main/scala/fruit/domain/Repository.scala
  src/main/scala/fruit/infrastructure/InMemoryRepository.scala
  src/test/scala/fruit/FruitTest.scala
Labels: cd, ci

#5 chore(ci): Testing workflow
  .github/workflows/testing.yaml
Labels: ci

#7 fix(ci): Update test pipeline
  .github/workflows/testing.yaml
  src/main/scala/Main.scala
Labels: ci

#9 ci: tagging pipeline
  .github/workflows/tagging.yaml
  .gitignore
  CHANGELOG.md
  package-lock.json
  package.json
  version.py
Labels: ci

#10 ci: release pipeline
  .github/workflows/release.yaml
Labels: ci

#11 ci: coverage pipeline
  .github/workflows/coverage.yaml
  docker-compose.dev.yaml
Labels: ci

#15 Fix: Detach docker compose
  .github/workflows/coverage.yaml
  README.md
Labels: ci

#16 fix(ci): Coverage pipeline
  .github/workflows/coverage.yaml
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ci

#20 feat: PostgreSQL connection and Migrations
  .dockerignore
  .github/workflows/coverage.yaml
  .github/workflows/testing.yaml
  CLI.md
  Dockerfile
  Makefile
  README.md
  build.sbt
  db/migrations/V1__init.sql
  db/migrations/V2__rename.sql
  docker-compose.yaml
  src/main/scala/Main.scala
  src/main/scala/fruit/infrastructure/PostgreSQLRepository.scala
  src/main/scala/migrations/PostgreSQLMigration.scala
  src/main/scala/shared/infrastructure/Environment.scala
  src/main/scala/shared/infrastructure/PostgreSQLPool.scala
  src/test/scala/fruit/FruitMemoryRepositoryTest.scala
  src/test/scala/fruit/FruitPostgreSQLRepositoryTest.scala
  volumes/.gitkeep
Labels: documentation, enhancement, ci

#24 chore: release 0.0.12
  .dockerignore
  .github/workflows/coverage.yaml
  .github/workflows/testing.yaml
  CHANGELOG.md
  CLI.md
  Dockerfile
  Makefile
  README.md
  build.sbt
  db/migrations/V1__init.sql
  db/migrations/V2__rename.sql
  docker-compose.yaml
  docs/spec.openapi.yaml
  package-lock.json
  package.json
  src/main/scala/Main.scala
  src/main/scala/fruit/infrastructure/PostgreSQLRepository.scala
  src/main/scala/migrations/PostgreSQLMigration.scala
  src/main/scala/shared/infrastructure/Environment.scala
  src/main/scala/shared/infrastructure/PostgreSQLPool.scala
  src/test/scala/fruit/FruitMemoryRepositoryTest.scala
  src/test/scala/fruit/FruitPostgreSQLRepositoryTest.scala
  volumes/.gitkeep
Labels: documentation, enhancement
