Repository hawks-atlanta/metadata-scala, pull requests merged in 2023-10, with the labels that each got.

#75 fix: Parse null-able extension field
  src/main/scala/files_metadata/infrastructure/MetadataControllers.scala
Labels: bug

#76 release: v0.10.3
  .github/workflows/testing.yaml
  CHANGELOG.md
  src/main/scala/files_metadata/application/FilesMetaUseCases.scala
  src/main/scala/files_metadata/domain/ArchiveMeta.scala
  src/main/scala/files_metadata/domain/FilesMetaRepository.scala
  src/main/scala/files_metadata/infrastructure/FilesMetaPostgresRepository.scala
  src/main/scala/files_metadata/infrastructure/MetadataControllers.scala
  src/test/scala/files_metadata/GetMetadata.scala
  src/test/scala/files_metadata/SharedWithMe.scala
  src/test/scala/files_metadata/UpdateToReady.scala
  version.json
Labels: bug, cd

#80 fix: Update controllers error handler
  src/main/scala/files_metadata/infrastructure/MetadataControllers.scala
Labels: bug

#78 feat: List files
  docs/rest/list_files.http
  docs/spec.openapi.yaml
  src/main/scala/files_metadata/application/FilesMetaUseCases.scala
  src/main/scala/files_metadata/domain/DomainExceptions.scala
  src/main/scala/files_metadata/domain/FileExtendedMeta.scala
  src/main/scala/files_metadata/domain/FilesMetaRepository.scala
  src/main/scala/files_metadata/infrastructure/FilesMetaPostgresRepository.scala
  src/main/scala/files_metadata/infrastructure/MetadataControllers.scala
  src/main/scala/files_metadata/infrastructure/MetadataRoutes.scala
  src/test/scala/files_metadata/FilesTestsUtils.scala
  src/test/scala/files_metadata/ListFilesInDirectories.scala
Labels: feature

#81 release: v0.11.0
  CHANGELOG.md
  docs/rest/list_files.http
  docs/spec.openapi.yaml
  src/main/scala/files_metadata/application/FilesMetaUseCases.scala
  src/main/scala/files_metadata/domain/DomainExceptions.scala
  src/main/scala/files_metadata/domain/FileExtendedMeta.scala
  src/main/scala/files_metadata/domain/FilesMetaRepository.scala
  src/main/scala/files_metadata/infrastructure/FilesMetaPostgresRepository.scala
  src/main/scala/files_metadata/infrastructure/MetadataControllers.scala
  src/main/scala/files_metadata/infrastructure/MetadataRoutes.scala
  src/test/scala/files_metadata/FilesTestsUtils.scala
  src/test/scala/files_metadata/ListFilesInDirectories.scala
  version.json
Labels: cd

#83 refactor: Add logs and fix Scala warnings
  src/main/scala/files_metadata/infrastructure/FilesMetaPostgresRepository.scala
  src/main/scala/files_metadata/infrastructure/MetadataControllers.scala
  src/main/scala/files_metadata/infrastructure/MetadataRoutes.scala
  src/main/scala/files_metadata/infrastructure/requests/MoveReqSchema.scala
  src/main/scala/shared/infrastructure/CaskHTTPRouter.scala
  src/main/scala/shared/infrastructure/StdoutLogger.scala
  src/test/scala/files_metadata/FilesTestsUtils.scala
  src/test/scala/files_metadata/ListFilesInDirectories.scala
Labels: refactor

#84 docs(http): Add bruno collection
  docs/bruno/bruno.json
  docs/bruno/can-read/can-read.bru
  docs/bruno/create-file/file-in-folder.bru
  docs/bruno/create-file/file-in-root.bru
  docs/bruno/create-file/file-no-extension.bru
  docs/bruno/create-file/folder-in-folder.bru
  docs/bruno/create-file/folder-in-root.bru
  docs/bruno/environments/development.bru
  docs/bruno/get-metadata/get-metadata.bru
  docs/bruno/list-files/files-in-folder.bru
  docs/bruno/list-files/files-in-root.bru
  docs/bruno/mark-as-ready/mark-as-ready.bru
  docs/bruno/move-file/move-file.bru
  docs/bruno/rename-file/rename-file.bru
  docs/bruno/share-file/share-file.bru
  docs/bruno/shared-with-me/shared-with-me.bru
  docs/bruno/shared-with-who/shared-with-who.bru
  docs/rest/can_read.http
  docs/rest/get_metadata.http
  docs/rest/get_shared_with_user.http
  docs/rest/get_shared_with_who.http
  docs/rest/list_files.http
  docs/rest/mark_as_ready.http
  docs/rest/move_file.http
  docs/rest/rename_file.http
  docs/rest/save_metadata.http
  docs/rest/share_file.http
Labels: documentation

#86 fix: Include files size
  docs/spec.openapi.yaml
  src/main/scala/files_metadata/domain/ArchiveMeta.scala
  src/main/scala/files_metadata/domain/FileExtendedMeta.scala
  src/main/scala/files_metadata/infrastructure/FilesMetaPostgresRepository.scala
  src/main/scala/files_metadata/infrastructure/MetadataControllers.scala
  src/main/scala/files_metadata/infrastructure/requests/CreationReqSchema.scala
Labels: bug

#87 release: v0.11.1
  CHANGELOG.md
  docs/bruno/bruno.json
  docs/bruno/can-read/can-read.bru
  docs/bruno/create-file/file-in-folder.bru
  docs/bruno/create-file/file-in-root.bru
  docs/bruno/create-file/file-no-extension.bru
  docs/bruno/create-file/folder-in-folder.bru
  docs/bruno/create-file/folder-in-root.bru
  docs/bruno/environments/development.bru
  docs/bruno/get-metadata/get-metadata.bru
  docs/bruno/list-files/files-in-folder.bru
  docs/bruno/list-files/files-in-root.bru
  docs/bruno/mark-as-ready/mark-as-ready.bru
  docs/bruno/move-file/move-file.bru
  docs/bruno/rename-file/rename-file.bru
  docs/bruno/share-file/share-file.bru
  docs/bruno/shared-with-me/shared-with-me.bru
  docs/bruno/shared-with-who/shared-with-who.bru
  docs/rest/can_read.http
  docs/rest/get_metadata.http
  docs/rest/get_shared_with_user.http
  docs/rest/get_shared_with_who.http
  docs/rest/list_files.http
  docs/rest/mark_as_ready.http
  docs/rest/move_file.http
  docs/rest/rename_file.http
  docs/rest/save_metadata.http
  docs/rest/share_file.http
  docs/spec.openapi.yaml
  src/main/scala/files_metadata/domain/ArchiveMeta.scala
  src/main/scala/files_metadata/domain/FileExtendedMeta.scala
  src/main/scala/files_metadata/infrastructure/FilesMetaPostgresRepository.scala
  src/main/scala/files_metadata/infrastructure/MetadataControllers.scala
  src/main/scala/files_metadata/infrastructure/MetadataRoutes.scala
  src/main/scala/files_metadata/infrastructure/requests/CreationReqSchema.scala
  src/main/scala/files_metadata/infrastructure/requests/MoveReqSchema.scala
  src/main/scala/shared/infrastructure/CaskHTTPRouter.scala
  src/main/scala/shared/infrastructure/StdoutLogger.scala
  src/test/scala/files_metadata/FilesTestsUtils.scala
  src/test/scala/files_metadata/ListFilesInDirectories.scala
  version.json
Labels: cd

#89 feat: Unshare file
  docs/bruno/shared-with-who/shared-with-who.bru
  docs/bruno/unshare-file/unshare-file.bru
  src/main/scala/files_metadata/application/FilesMetaUseCases.scala
  src/main/scala/files_metadata/domain/FilesMetaRepository.scala
  src/main/scala/files_metadata/infrastructure/FilesMetaPostgresRepository.scala
  src/main/scala/files_metadata/infrastructure/MetadataControllers.scala
  src/main/scala/files_metadata/infrastructure/MetadataRoutes.scala
  src/test/scala/files_metadata/FilesTestsUtils.scala
  src/test/scala/files_metadata/UnshareFile.scala
Labels: feature

#90 release: v0.12.0
  CHANGELOG.md
  docs/bruno/shared-with-who/shared-with-who.bru
  docs/bruno/unshare-file/unshare-file.bru
  src/main/scala/files_metadata/application/FilesMetaUseCases.scala
  src/main/scala/files_metadata/domain/FilesMetaRepository.scala
  src/main/scala/files_metadata/infrastructure/FilesMetaPostgresRepository.scala
  src/main/scala/files_metadata/infrastructure/MetadataControllers.scala
  src/main/scala/files_metadata/infrastructure/MetadataRoutes.scala
  src/test/scala/files_metadata/FilesTestsUtils.scala
  src/test/scala/files_metadata/UnshareFile.scala
  version.json
Labels: cd

#92 release: v0.13.0
  CHANGELOG.md
  docs/bruno/remove-file/remove-file.bru
  docs/bruno/share-file/share-file.bru
  docs/spec.openapi.yaml
  src/main/resources/migrations/V1.2.1.sql
  src/main/scala/files_metadata/application/FilesMetaUseCases.scala
  src/main/scala/files_metadata/domain/FilesMetaRepository.scala
  src/main/scala/files_metadata/infrastructure/FilesMetaPostgresRepository.scala
  src/main/scala/files_metadata/infrastructure/MetadataControllers.scala
  src/main/scala/files_metadata/infrastructure/MetadataRoutes.scala
  src/test/scala/files_metadata/DeleteFile.scala
  src/test/scala/files_metadata/FilesTestsUtils.scala
  version.json
Labels: cd
